### ISSUE TITLE
Bug: tree view 中文件图标显示错误

### ISSUE THREAD

**Issue by shigma** [Symbolk/somanyconflicts#12]
![image](https://user-images.githubusercontent.com/33423008/121592049-ced0c800-ca6c-11eb-9f68-a8717fc7ebb6.png)

这里明明是一个文件，却显示成了文件夹图标。

当然，更好的情况是这里与 vscode 其他地方显示相统一：

![image](https://user-images.githubusercontent.com/33423008/121592207-faec4900-ca6c-11eb-8922-ffe388cc6648.png)

不确定能否做到。

**Comment by Symbolk** [comment]
这部分代码目前是只在你本地吗？

**Comment by TsukimiRini** [comment]
我在pr#14里加了这个问题的fix
