### ISSUE TITLE
TreeItem label optimization

### ISSUE THREAD

**Issue by Symbolk** [Symbolk/somanyconflicts#22]
TreeItem的label有时会出现不完整的内容，原因应该是在生成时doc.getText(range)的range问题

![Kapture 2021-06-21 at 14 23 36](https://user-images.githubusercontent.com/14107297/122716092-68ce1700-d29c-11eb-89a6-0819d2c7661a.gif)

**Comment by TsukimiRini** [comment]
已修复，现在label会显示被resolve后conflict的内容。但是如果resolve后conflict为空label依然为空，即使标记的代码行号对应到文档中存在内容
