### ISSUE TITLE
Activating extension failed

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [Symbolk/somanyconflicts#28]
Issue Type: <b>Bug</b>

mainThreadExtensionService.ts:95 Activating extension 'Symbolk.somanyconflicts' failed: \\?\$HOME\.vscode\extensions\symbolk.somanyconflicts-0.0.5\node_modules\tree-sitter\build\Release\tree_sitter_runtime_binding.node is not a valid Win32 application.
\\?\$HOME\.vscode\extensions\symbolk.somanyconflicts-0.0.5\node_modules\tree-sitter\build\Release\tree_sitter_runtime_binding.node.

Extension version: 0.0.5
VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) Gold G5400 CPU @ 3.70GHz (4 x 3696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.48GB free)|
|Process Argv|--crash-reporter-id 2ecdc59c-7d55-48a0-beaf-451bf71a6cf4|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805:30301674
pythonvspyt200cf:30331938
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
bridge0708:30335490

```

</details>

**Comment by Symbolk** [comment]
Thanks for the issue, this is a known bug under Windows, the market version is built for macOS, we will release a Windows version on Github soon.

**Comment by Symbolk** [comment]
@sschneider-ihre-pvs Hi, I recently update the native module tree-sitter to web assembly version, can you download the extension again and have a try?

**Comment by sschneider-ihre-pvs** [comment]
sure i can try that
